from pathlib import Path
import pandas as pd

from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet


# ==========================================================
# CONFIGURATION
# ==========================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

POLICY_CSV = PROJECT_ROOT / "data" / "policies" / "policy_master.csv"

OUTPUT_FOLDER = PROJECT_ROOT / "data" / "policies" / "pdfs"

OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

styles = getSampleStyleSheet()


# ==========================================================
# LOAD POLICIES
# ==========================================================

def load_policies():

    policies = pd.read_csv(POLICY_CSV)

    print(f"Policies Loaded : {len(policies)}")

    return policies

# ==========================================================
# POLICY CONTENT
# ==========================================================

def get_coverage(policy_type):

    policy_type = str(policy_type).lower()

    if "third" in policy_type:
        return [
            "✓ Third Party Liability",
            "✗ Own Vehicle Damage",
            "✗ Theft",
            "✗ Fire",
            "✗ Flood Damage",
        ]

    elif "zero" in policy_type:
        return [
            "✓ Collision Damage",
            "✓ Theft",
            "✓ Fire",
            "✓ Flood Damage",
            "✓ Glass Breakage",
            "✓ Natural Disaster",
            "✓ Third Party Liability",
            "✓ Nil Depreciation",
            "✓ Plastic Parts",
            "✓ Consumables",
        ]

    else:
        return [
            "✓ Collision Damage",
            "✓ Theft",
            "✓ Fire",
            "✓ Flood Damage",
            "✓ Glass Breakage",
            "✓ Natural Disaster",
            "✓ Third Party Liability",
        ]


def get_required_documents():

    return [
        "Claim Form",
        "Driving License",
        "Vehicle RC",
        "Policy Copy",
        "Repair Estimate",
        "Vehicle Images",
        "Police FIR (if applicable)"
    ]


def get_claim_process():

    return [
        "1. Register Claim",
        "2. Upload Vehicle Images",
        "3. AI Damage Assessment",
        "4. Surveyor Verification",
        "5. Policy Verification",
        "6. Fraud Detection",
        "7. Claim Approval",
        "8. Claim Settlement"
    ]


def get_exclusions():

    return [
        "Driving under alcohol",
        "Mechanical wear and tear",
        "Illegal modifications",
        "Racing activities",
        "War / Nuclear damage",
        "Intentional damage",
        "Expired Driving License"
    ]
from reportlab.pdfgen import canvas


def add_footer(canvas, doc):
    canvas.saveState()

    canvas.setFont("Helvetica", 8)

    canvas.drawString(
        40,
        20,
        "Generated by IntelliClaim AI | Confidential | Version 1.0"
    )

    canvas.restoreState()

# ==========================================================
# CREATE PDF
# ==========================================================

def create_policy_pdf(policy):

    pdf_name = f"{policy['Policy_Number']}.pdf"

    pdf_path = OUTPUT_FOLDER / pdf_name

    document = SimpleDocTemplate(
        str(pdf_path),
        title=f"Insurance Policy - {policy['Policy_Number']}",
        author="IntelliClaim AI",
        subject="Vehicle Insurance Policy Document",
    )

    coverage = get_coverage(policy["Policy_Type"])
    documents = get_required_documents()
    claim_process = get_claim_process()
    exclusions = get_exclusions()

    story = []

    story.append(
        Paragraph(
            "<b>INTELLICLAIM INSURANCE POLICY</b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "<br/><br/>",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Policy Number : {policy['Policy_Number']}",
            styles["Heading2"]
        )
    )
    story.append(
        Paragraph(
           f"Insurance Provider : {policy['Insurance_Provider']}",
           styles["Normal"]
        )
    )

    story.append(
        Paragraph(
           f"Premium Amount : Rs. {policy['Premium_Amount']}",
           styles["Normal"]
        )
    )

    story.append(
        Paragraph(
           f"Sum Insured : Rs. {policy['Sum_Insured']}",
           styles["Normal"]
        )
    )


    story.append(
        Paragraph(
            f"Policy Type : {policy['Policy_Type']}",
            styles["Normal"]
        )
    )

    

    story.append(
        Paragraph(
            f"Deductible : Rs. {policy['Deductible']}",
            styles["Normal"]
        )
    )
    story.append(
        Paragraph(
            f"Roadside Assistance : Rs. {policy['Roadside_Assistance']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
           f"Engine Protection : {policy['Engine_Protection']}",
           styles["Normal"]
        )
    )

    story.append(
        Paragraph(
           f"Personal Accident Cover : {policy['Personal_Accident_Cover']}",
           styles["Normal"]
        )
    )

    story.append(
        Paragraph(
           f"Valid From : {policy['Valid_From']}",
           styles["Normal"]
        )
    )

    story.append(
        Paragraph(
           f"Valid To : {policy['Valid_To']}",
           styles["Normal"]
        )
    )

    story.append(
        Paragraph(
           f"Policy Status : {policy['Policy_Status']}",
           styles["Normal"]
        )
    )


    # ---------------------------------------------------------
    # Coverage
    # ---------------------------------------------------------

    story.append(Paragraph("<br/><b>Coverage Details</b>", styles["Heading2"]))

    for item in coverage:
        story.append(Paragraph(item, styles["Normal"]))


    # ---------------------------------------------------------
    # Optional Add-ons
    # ---------------------------------------------------------

    story.append(Paragraph("<br/><b>Optional Add-ons</b>", styles["Heading2"]))

    story.append(Paragraph(f"Roadside Assistance : {policy['Roadside_Assistance']}",
        styles["Normal"]
        )
    )

    story.append(
        Paragraph(
        f"Engine Protection : {policy['Engine_Protection']}",
        styles["Normal"]
        )
    )

    story.append(
        Paragraph(
        f"Personal Accident Cover : {policy['Personal_Accident_Cover']}",
        styles["Normal"]
        )
    )


    # ---------------------------------------------------------
    # Required Documents
    # ---------------------------------------------------------

    story.append(Paragraph("<br/><b>Required Documents</b>", styles["Heading2"]))

    for doc in documents:
        story.append(Paragraph(f"• {doc}", styles["Normal"]))


    # ---------------------------------------------------------
    # Claim Process
    # ---------------------------------------------------------

    story.append(Paragraph("<br/><b>Claim Process</b>", styles["Heading2"]))

    for step in claim_process:
        story.append(Paragraph(step, styles["Normal"]))


    # ---------------------------------------------------------
    # Exclusions
    # ---------------------------------------------------------

    story.append(Paragraph("<br/><b>General Exclusions</b>", styles["Heading2"]))

    for ex in exclusions:
        story.append(
            Paragraph(
               f"• {ex}",
               styles["Normal"]
            )
        )


    # ---------------------------------------------------------
    # Customer Support
    # ---------------------------------------------------------

    story.append(Paragraph("<br/><b>Customer Support</b>", styles["Heading2"]))

    story.append(
        Paragraph(
          "Email : support@intelliclaim.ai",
           styles["Normal"]
        )
    )

    story.append(
        Paragraph(
         "Phone : +91-1800-100-2026",
          styles["Normal"]
        )
    )

    story.append(
        Paragraph(
         "Website : www.intelliclaim.ai",
          styles["Normal"]
        )
    )


    # ---------------------------------------------------------
    # Terms
    # ---------------------------------------------------------

    story.append(Paragraph("<br/><b>Terms & Conditions</b>", styles["Heading2"]))

    story.append(
        Paragraph(
            "Claims are processed only after successful policy verification. "
            "The insurer reserves the right to reject fraudulent or incomplete claims. "
            "Coverage is subject to policy terms, exclusions, deductibles, and applicable regulations.",
            styles["Normal"]
        )
    )

    document.build(
        story,
        onFirstPage=add_footer,
        onLaterPages=add_footer
    )


    # ==========================================================
    # GENERATE PDFs
    # ==========================================================

def generate_pdfs(policies):

    for _, policy in policies.iterrows():

        create_policy_pdf(policy)

    print(f"\nGenerated {len(policies)} Policy PDFs")

# ==========================================================
# VALIDATE PDFs
# ==========================================================

def validate_pdfs(policies):

    missing = []

    empty = []

    for _, policy in policies.iterrows():

        pdf = OUTPUT_FOLDER / f"{policy['Policy_Number']}.pdf"

        if not pdf.exists():
            missing.append(pdf.name)

        elif pdf.stat().st_size == 0:
            empty.append(pdf.name)

    print("\nValidation Report")
    print("-" * 40)

    print(f"Expected PDFs : {len(policies)}")
    print(f"Missing PDFs  : {len(missing)}")
    print(f"Empty PDFs    : {len(empty)}")

    if missing:
        print("\nMissing Files:")
        for f in missing:
            print(f" - {f}")

    if empty:
        print("\nEmpty Files:")
        for f in empty:
            print(f" - {f}")

# ==========================================================
# STATISTICS
# ==========================================================

def print_statistics(policies):

    print("\n" + "=" * 60)
    print("PDF GENERATION SUMMARY")
    print("=" * 60)

    print(f"Policies Loaded : {len(policies)}")
    print(f"PDFs Generated  : {len(list(OUTPUT_FOLDER.glob('*.pdf')))}")

    print("\nPolicy Types")

    print(policies["Policy_Type"].value_counts())

    print("\nInsurance Providers")

    print(policies["Insurance_Provider"].value_counts())

    print("=" * 60)

# ==========================================================
# MAIN
# ==========================================================

def main():

    print("=" * 60)
    print("INTELLICLAIM AI - POLICY PDF GENERATOR (PART 1)")
    print("=" * 60)

    policies = load_policies()

    generate_pdfs(policies)

    validate_pdfs(policies)

    print_statistics(policies)

    print("\nPDF Location:")
    print(OUTPUT_FOLDER)

    print("\n" + "=" * 60)
    print("PART 3 COMPLETED SUCCESSFULLY")
    print("=" * 60)


if __name__ == "__main__":
    main()