import streamlit as st


def show_crew_report():

    st.subheader("🤖 Latest CrewAI Report")

    st.info(
        """
Damage Summary

Rear bumper damaged.

Coverage

Covered under comprehensive policy.

Decision

Approved.

Generated by CrewAI.
"""
    )