from langchain_community.document_loaders import PyPDFLoader

from rag.config import POLICY_PDF_DIR


# ==========================================================
# LOAD POLICY DOCUMENTS
# ==========================================================

def load_policy_documents():
    """
    Load all policy PDFs and return LangChain Document objects.
    """

    pdf_files = sorted(POLICY_PDF_DIR.glob("*.pdf"))

    if not pdf_files:
        raise FileNotFoundError(
            f"No PDF files found in {POLICY_PDF_DIR}"
        )

    all_documents = []

    print("=" * 60)
    print("LOADING POLICY DOCUMENTS")
    print("=" * 60)

    for pdf in pdf_files:

        loader = PyPDFLoader(str(pdf))

        documents = loader.load()

        # ------------------------------------------------------
        # Clean content & metadata
        # ------------------------------------------------------

        for doc in documents:

            # Remove repeated footer/header
            doc.page_content = (
                doc.page_content
                .replace(
                    "Generated by IntelliClaim AI | Confidential | Version 1.0",
                    ""
                )
                .strip()
            )

            # Keep only useful metadata
            doc.metadata = {
                "policy_number": pdf.stem,
                "page": doc.metadata["page"],
                "source": str(pdf),
            }

        all_documents.extend(documents)

        print(f"{pdf.name:<20} Pages : {len(documents)}")

    print("\n" + "=" * 60)
    print(f"PDF Files Loaded : {len(pdf_files)}")
    print(f"Total Pages      : {len(all_documents)}")
    print("=" * 60)

    return all_documents


# ==========================================================
# PREVIEW DOCUMENTS
# ==========================================================

def preview_documents(documents, num_docs=2):
    """
    Preview the first few loaded documents.
    """

    print("\n" + "=" * 60)
    print("DOCUMENT PREVIEW")
    print("=" * 60)

    for i, doc in enumerate(documents[:num_docs], start=1):

        print(f"\nDocument {i}")
        print("-" * 60)

        print("Metadata:")

        for key, value in doc.metadata.items():
            print(f"{key} : {value}")

        print("\nCharacters :", len(doc.page_content))

        print("\nContent Preview:\n")

        print(doc.page_content[:700])

        print("\n" + "=" * 60)


# ==========================================================
# MAIN
# ==========================================================

def main():

    documents = load_policy_documents()

    preview_documents(documents)


if __name__ == "__main__":
    main()