"""initial schema

Revision ID: 940e776d4421
Revises: 
Create Date: 2026-08-01 20:16:52.681005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '940e776d4421'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('driving_license_no', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('driving_license_no'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_table('policies',
    sa.Column('policy_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('insurance_provider', sa.String(length=100), nullable=False),
    sa.Column('premium_amount', sa.Float(), nullable=False),
    sa.Column('sum_insured', sa.Float(), nullable=False),
    sa.Column('deductible', sa.Float(), nullable=False),
    sa.Column('roadside_assistance', sa.String(length=10), nullable=False),
    sa.Column('engine_protection', sa.String(length=10), nullable=False),
    sa.Column('personal_accident_cover', sa.String(length=10), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('policy_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('policy_number')
    )
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=False)
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('policy_number', sa.String(length=20), nullable=False),
    sa.Column('accident_date', sa.Date(), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('damage_type', sa.String(length=50), nullable=False),
    sa.Column('accident_description', sa.String(), nullable=False),
    sa.Column('estimated_repair_cost', sa.Float(), nullable=False),
    sa.Column('claim_amount', sa.Float(), nullable=False),
    sa.Column('fraud_label', sa.String(length=20), nullable=False),
    sa.Column('fraud_score', sa.Integer(), nullable=False),
    sa.Column('claim_status', sa.String(length=30), nullable=False),
    sa.Column('inspection_status', sa.String(length=30), nullable=False),
    sa.Column('cv_status', sa.String(length=30), nullable=False),
    sa.Column('nlp_status', sa.String(length=30), nullable=False),
    sa.Column('rag_status', sa.String(length=30), nullable=False),
    sa.Column('final_decision', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['policy_number'], ['policies.policy_number'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index(op.f('ix_claims_claim_id'), 'claims', ['claim_id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('decision_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=20), nullable=True),
    sa.Column('coverage', sa.String(length=20), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('claim_id')
    )
    op.create_table('ai_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=20), nullable=False),
    sa.Column('image_name', sa.String(), nullable=False),
    sa.Column('detections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('repair_cost', sa.Float(), nullable=True),
    sa.Column('repair_days', sa.Integer(), nullable=True),
    sa.Column('repairable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_detections_id'), 'ai_detections', ['id'], unique=False)
    op.create_table('nlp_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=20), nullable=False),
    sa.Column('accident_type', sa.String(), nullable=True),
    sa.Column('vehicle_part', sa.String(), nullable=True),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('cause', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nlp_analysis_id'), 'nlp_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nlp_analysis_id'), table_name='nlp_analysis')
    op.drop_table('nlp_analysis')
    op.drop_index(op.f('ix_ai_detections_id'), table_name='ai_detections')
    op.drop_table('ai_detections')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_claims_claim_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
